gui:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - red
    selectedLineBgColor:
      - '#202020'
      - bold
  nerdFontsVersion: "3"
quitOnTopLevelReturn: true
customCommands: # https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium
  - key: b
    command: tig blame -- {{.SelectedFile.Name}}
    context: files
    description: blame file at tree
    subprocess: yes
  - key: b
    command: tig blame {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: blame file at revision
    subprocess: yes
  - key: B
    command: tig blame -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: blame file at tree
    subprocess: yes
