os:
  editPreset: 'nvim'
gui:
  theme:
    activeBorderColor:
      - yellow
      - bold
    inactiveBorderColor:
      - '#888888'
    selectedLineBgColor:
      - '#222222'
      - bold
    optionsTextColor:
      - green
  nerdFontsVersion: "3"
quitOnTopLevelReturn: true
customCommands: # https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium
  - key: b
    command: tig blame -- {{.SelectedFile.Name}}
    context: files
    description: Blame file at tree
  - key: b
    command: tig blame {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: Blame file at revision
  - key: B
    command: tig blame -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: Blame file at tree
