matches:
  # jira
  - trigger: ":jci" # code inline
    replace: "{{{color:#00875A}$|${color}}}" #replace: "{{{color:#337733}$|${color}}}"
  - trigger: ":jcn" # code noformat
    replace: "{noformat:bgColor=#eeeeee}\n$|$\n{noformat}"
  - trigger: ":jcp" # code python
    replace: "{code:python|bgColor=#eeeeee}\n$|$\n{code}"
  - trigger: ":jcs" # code sql
    replace: "{code:sql|bgColor=#eeeeee}\n$|$\n{code}"

  # general
  - trigger: ":tc"
    replace: "Thanks,\nConor"
  - trigger: :euro
    replace: €
