# reliability
disable_x11_fast_inject: true
inject_delay: 1
key_delay: 1

matches:
  # jira
  - trigger: ":jci" # code inline
    replace: "{{{color:#00875A}$|${color}}}" #replace: "{{{color:#337733}$|${color}}}"
  - trigger: ":jcn" # code noformat
    replace: "{noformat:bgColor=#ededed}\n$|$\n{noformat}"
  - trigger: ":jcp" # code python
    replace: "{code:python|bgColor=#ededed}\n$|$\n{code}"
  - trigger: ":jcs" # code sql
    replace: "{code:sql|bgColor=#ededed}\n$|$\n{code}"

  # general
  - trigger: ":tc"
    replace: "Thanks,\nConor"
  - trigger: :euro
    replace: €

  # time / date
  - trigger: ":time"
    replace: "{{h_m}}"
    vars:
      - name: h_m
        type: date
        params:
          format: "%H%M"
  - trigger: ":date"
    replace: "{{y_m_d}}"
    vars:
      - name: y_m_d
        type: date
        params:
          format: "%Y%m%d"
